name: Executar limpeza de dados com Python

on:
  push:
    paths:
      - 'data/**'
      - 'limpeza.py'
      - '.github/workflows/python-ci.yml'

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências (se houver)
        run: |
          pip install -r requirements.txt || echo "Nenhum requirements.txt encontrado"

      - name: Executar script de limpeza
        run: python limpeza.py

      - name: Fazer commit do resultado da limpeza
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/
          git commit -m "Atualiza dados processados automaticamente" || echo "Sem alterações para commitar"
          git push
