name: Executar limpeza de dados com Python

on:
  push:
    paths:
      - 'data/**'
      - 'limpeza.py'
      - '.github/workflows/python-ci.yml'

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências (se houver)
        run: |
          pip install -r requirements.txt || echo "Nenhum requirements.txt encontrado"

      - name: Executar script de limpeza
        run: python limpeza.py

      - name: Commit e push dos arquivos gerados
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Arquivo dados_limpos.csv atualizado automaticamente pelo GitHub Actions'
          add: 'output/dadoslimpos.csv'
